[package]
name = "rex"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "rex"
test = false
bench = false

[dependencies]
tui = "0.19.0"
crossterm = "0.25.0"  
rusqlite = { version = "0.28.0", features = ["bundled"] }
chrono = "0.4.19"
open = "3.0.1"
atty = "0.2.14"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.140", features = ["derive"]}
dirs = "4.0.0"