[package]
name = "rex-tui"
version = "0.1.14"
edition = "2021"
authors = ["TheRustyPickle <rusty.pickle94@gmail.com>"]
readme = "README.md"
description = """
A TUI for managing Incomes and Expenses
"""
homepage = "https://github.com/TheRustyPickle/Rex"
repository = "https://github.com/TheRustyPickle/Rex"
license = "MIT"
keywords = ["tui", "terminal", "tui-app", "ratatui", "terminal-ui"]
categories = ["command-line-utilities"]
exclude = ["logo.png"]

[[bin]]
name = "rex"
path = "src/main.rs"
test = false
bench = false

[dependencies]
crossterm = "0.25.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.34"
open = "5.0.1"
atty = "0.2.14"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"]}
dirs = "5.0.1"
thousands = "0.2.0"
semver = "1.0.22"
ratatui = "0.26.1"
strsim = "0.11.0"
serde_json = "1.0.114"
