[package]
name = "rex-tui"
version = "0.1.16"
edition = "2021"
authors = ["TheRustyPickle <rusty.pickle94@gmail.com>"]
readme = "README.md"
description = """
A TUI for managing Incomes and Expenses
"""
homepage = "https://github.com/TheRustyPickle/Rex"
repository = "https://github.com/TheRustyPickle/Rex"
license = "MIT"
keywords = ["tui", "terminal", "tui-app", "ratatui", "terminal-ui"]
categories = ["command-line-utilities"]
exclude = ["logo.png"]

[[bin]]
name = "rex"
path = "src/main.rs"
test = false
bench = false

[dependencies]
crossterm = "0.27.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.38"
open = "5.1.4"
atty = "0.2.14"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.203", features = ["derive"]}
dirs = "5.0.1"
thousands = "0.2.0"
semver = "1.0.23"
ratatui = "0.26.3"
strsim = "0.11.1"
serde_json = "1.0.117"
